// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDXz3ZLD5ejGhsC20FserCnQtSiwVvKc4',
    appId: '1:152670938013:web:3a94f304018b8514830574',
    messagingSenderId: '152670938013',
    projectId: 'ecommerce-app-8dfa9',
    authDomain: 'ecommerce-app-8dfa9.firebaseapp.com',
    storageBucket: 'ecommerce-app-8dfa9.firebasestorage.app',
    measurementId: 'G-30H0B450SR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwohTFKLE_h3KkBiYusySXvLsS9h5I9_Y',
    appId: '1:152670938013:android:7f925b9b5bb7909a830574',
    messagingSenderId: '152670938013',
    projectId: 'ecommerce-app-8dfa9',
    storageBucket: 'ecommerce-app-8dfa9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0CF7RrQgGFTYeIF-IZ-EuNQTwAoEBu54',
    appId: '1:152670938013:ios:8228fb9fbf93a971830574',
    messagingSenderId: '152670938013',
    projectId: 'ecommerce-app-8dfa9',
    storageBucket: 'ecommerce-app-8dfa9.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0CF7RrQgGFTYeIF-IZ-EuNQTwAoEBu54',
    appId: '1:152670938013:ios:8228fb9fbf93a971830574',
    messagingSenderId: '152670938013',
    projectId: 'ecommerce-app-8dfa9',
    storageBucket: 'ecommerce-app-8dfa9.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDXz3ZLD5ejGhsC20FserCnQtSiwVvKc4',
    appId: '1:152670938013:web:e11a2361ccef93cb830574',
    messagingSenderId: '152670938013',
    projectId: 'ecommerce-app-8dfa9',
    authDomain: 'ecommerce-app-8dfa9.firebaseapp.com',
    storageBucket: 'ecommerce-app-8dfa9.firebasestorage.app',
    measurementId: 'G-SNB05CPEWG',
  );
}
